### ISSUE TITLE
QB64 Interpreter bug

### ISSUE THREAD

**Issue by bmac100** [FellippeHeitor/QB64-interpreter#1]
The exponent operator does not work, i.e. 7^2

**Comment by FellippeHeitor** [comment]
Hummm, thanks for reporting that.

**Comment by FellippeHeitor** [comment]
New operator added!
![2018-10-21 19_34_22-untitled](https://user-images.githubusercontent.com/10699359/47273290-8507dc00-d568-11e8-8fb5-458f2960955e.png)
